//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCreatePackage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageUpdateRecord
    {
        public int Id { get; set; }
        public int PackageId { get; set; }
        public string PackageName { get; set; }
        public string PackageUpdateVersion { get; set; }
        public System.DateTime PackageUpdateTime { get; set; }
    }
}
