//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCreatePackage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int Id { get; set; }
        public int PackageId { get; set; }
        public string PackageName { get; set; }
        public string PackageDownloadPageUrl { get; set; }
        public int PackageStatus { get; set; }
        public string PackageXPath { get; set; }
        public string HtmlElementId { get; set; }
        public string HtmlElementAttr { get; set; }
        public int PackageDownloadUrlType { get; set; }
        public string PackageCurrentVersion { get; set; }
        public System.DateTime LastCheckDate { get; set; }
        public System.DateTime PackageUpdateTime { get; set; }
        public string PackageSHA1Code { get; set; }
    }
}
