//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCreatePackage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int Id { get; set; }
        public int PackageId { get; set; }
        public string PackageName { get; set; }
        public string PackageDownLoadUrl { get; set; }
        public int PackageStatus { get; set; }
        public string PackageCurrentVersion { get; set; }
        public System.DateTime LastCheckDate { get; set; }
        public System.DateTime PackageUpdateTime { get; set; }
        public string PackageXPath { get; set; }
    }
}
